language: generic
sudo: false
dist: trusty

env:
    global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - BUILD_TESTING=false
    - DM_MAPFILE="loadallmaps"
    matrix:
    - BUILD_TOOLS=true
    - BUILD_TESTING=true
    - BUILD_TESTING=false

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
      - python3
      - python3-pip

before_install:
  - pip install --user awscli
  - pip3 install --user requests
  - pip3 install --user pyyaml
  - pip3 install --user python-dateutil
  - pip3 install --user bs4
  - export PATH=$PATH:$HOME/.local/bin

install:
  - tools/travis/install_build_tools.sh

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_changelog.sh
  - tools/travis/build_tools.sh
  - tools/travis/build_byond.sh
  - tools/travis/upload_artifacts.sh
